#!/bin/bash

###############################################################################
# Klyptr Studio - GitHub Issues & Labels Creator (Standalone)
# 
# This script ONLY creates GitHub labels and issues
# Use this when services already exist in GitHub but issues haven't been created yet
# This script creates GitHub issues from JSON config
# Fixes multi-line body issue by using temp files
# ============================================

set -e

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper functions
error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

info() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

heading() {
    echo ""
    echo -e "${BLUE}════════════════════════════════════════"
    echo "  $1"
    echo "════════════════════════════════════════${NC}"
    echo ""
}

# Check if config file provided
if [ -z "$1" ]; then
    echo "Usage: $0 <config-file.json>"
    echo "Example: $0 FINAL-new-services-config.json"
    exit 1
fi

CONFIG_FILE="$1"

# Validate config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    error "Config file not found: $CONFIG_FILE"
    exit 1
fi

heading "Creating GitHub Issues from Config"

info "Config file: $CONFIG_FILE"
info "Organization: Klyptr-Studio"

# Check prerequisites
command -v gh >/dev/null 2>&1 || { error "GitHub CLI not installed"; exit 1; }
command -v jq >/dev/null 2>&1 || { error "jq not installed"; exit 1; }

success "Prerequisites validated"

# Create temp directory for issue bodies
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

info "Temp directory: $TEMP_DIR"

# ============================================
# Extract and create issues
# ============================================

heading "Creating Issues"

CREATED=0
FAILED=0
SKIPPED=0

# Get number of services
SERVICES_COUNT=$(jq '.services | length' "$CONFIG_FILE")
info "Services found: $SERVICES_COUNT"

# Iterate through each service
for ((i = 0; i < SERVICES_COUNT; i++)); do
    SERVICE_NAME=$(jq -r ".services[$i].name" "$CONFIG_FILE")
    REPO_NAME=$(echo "$SERVICE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    FULL_REPO="Klyptr-Studio/$REPO_NAME"
    
    echo ""
    info "Service: $SERVICE_NAME"
    
    # Get issues for this service
    ISSUES_COUNT=$(jq ".services[$i].issues | length" "$CONFIG_FILE")
    
    for ((j = 0; j < ISSUES_COUNT; j++)); do
        TITLE=$(jq -r ".services[$i].issues[$j].title" "$CONFIG_FILE")
        DESCRIPTION=$(jq -r ".services[$i].issues[$j].description" "$CONFIG_FILE")
        TYPE=$(jq -r ".services[$i].issues[$j].type // \"type:feature\"" "$CONFIG_FILE")
        PRIORITY=$(jq -r ".services[$i].issues[$j].priority // \"priority:medium\"" "$CONFIG_FILE")
        
        # Create labels string
        LABELS="$TYPE,$PRIORITY"
        
        # Create temp file for issue body
        BODY_FILE="$TEMP_DIR/issue_${i}_${j}.md"
        cat > "$BODY_FILE" << 'BODY_EOF'
BODY_EOF
        echo "$DESCRIPTION" >> "$BODY_FILE"
        echo "" >> "$BODY_FILE"
        echo "*Auto-generated by Klyptr Studio*" >> "$BODY_FILE"
        
        # Check if issue already exists
        if gh issue list --repo "$FULL_REPO" --search "$TITLE" --json title --jq '.[] | select(.title == "'$TITLE'")' 2>/dev/null | grep -q .; then
            info "  ⊘ Issue already exists: $TITLE"
            ((SKIPPED++))
            continue
        fi
        
        # Create issue using body file (fixes multi-line issue)
        if gh issue create \
            --repo "$FULL_REPO" \
            --title "$TITLE" \
            --body-file "$BODY_FILE" \
            --label "$LABELS" \
            > /dev/null 2>&1; then
            success "  ✓ Created: $TITLE"
            ((CREATED++))
        else
            error "  ✗ Failed: $TITLE"
            ((FAILED++))
        fi
    done
done

# ============================================
# Summary
# ============================================

heading "Summary"

echo -e "${GREEN}Created:${NC}  $CREATED issues"
echo -e "${YELLOW}Skipped:${NC}  $SKIPPED issues (already exist)"
echo -e "${RED}Failed:${NC}   $FAILED issues"
echo ""

if [ $FAILED -gt 0 ]; then
    error "Some issues failed to create. Check repo names and permissions."
    exit 1
fi

success "GitHub issues created successfully!"